kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.redis.banking.app.name }}-config
  namespace: {{ .Values.redis.banking.app.namespace }}
data:
  REDIS_HOST: {{ .Values.redis.banking.app.name }}-redb.{{ .Values.redis.banking.app.namespace }}.svc.cluster.local
  REDIS_PORT: '{{ default 12000 .Values.redis.banking.app.db.databasePort }}'
  SPRING_PROFILE: {{ default "openshift" .Values.redis.banking.app.spring.profile }}
  STOMP_HOST: {{ .Values.redis.banking.app.name }}-{{ .Values.redis.banking.app.namespace }}.apps.uki-okd.demo.redislabs.com
  STOMP_PORT: '{{ .Values.redis.banking.app.stomp.port }}'
  STOMP_PROTOCOL: {{ .Values.redis.banking.app.stomp.protocol }}