kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.redis.banking.app.name }}-db-auth
  annotations:
{{ toYaml .Values.redis.banking.app.annotations | indent 4 }}
data:
  password: {{ .Values.redis.banking.app.secret.db.password | b64enc }}
type: Opaque