apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: {{ .Values.redis.banking.app.name }}-redb
  namespace: {{ .Values.redis.banking.app.namespace }}
spec: {{ if .Values.redis.banking.app.db.modules }}
  modulesList:
    {{- range .Values.redis.banking.app.db.modules }}
    - name: {{ .name }}
      version: {{ .version }}
    {{- end }} {{ end }}
  redisEnterpriseCluster:
    name: {{ default "rec" .Values.redis.banking.app.db.clusterName }}
  shardCount: {{ default 1 .Values.redis.banking.app.db.shardCount }}
  shardsPlacement: {{ default "dense" .Values.redis.banking.app.db.shardsPlacement }}
  databasePort: {{ default 12000 .Values.redis.banking.app.db.databasePort }}
  databaseSecretName: {{ .Values.redis.banking.app.name }}-auth
  memorySize: {{ default "5GB" .Values.redis.banking.app.db.memorySize }}