---
apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.redis.banking.app.annotations | indent 4 }}
  labels:
    expose: "true"
{{ toYaml .Values.redis.banking.app.labels | indent 4 }}
  name: {{ .Values.redis.banking.app.name }}-service
spec:
  ports:
    {{- range .Values.redis.banking.app.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{ .Values.redis.banking.app.labels.app }}
    group: {{ .Values.redis.banking.app.labels.group }}