kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.redis.banking.app.name }}-auth
  annotations:
{{ toYaml .Values.redis.banking.app.annotations | indent 4 }}
data:
  username: {{ .Values.redis.banking.app.secret.user.username | b64enc }}
  password: {{ .Values.redis.banking.app.secret.user.password | b64enc }}
  roles: {{ .Values.redis.banking.app.secret.user.roles | b64enc }}
type: Opaque